### ISSUE TITLE
Camera#save_to_disk produces questionable floating-point PPMs

### ISSUE THREAD

**Issue by bluelhf** [rust-adventure/raytracing-in-one-weekend#1]
While not explicitly mentioned in any specification I've found, it seems to be generally assumed that P3's ASCII values are integers (for example, FFmpeg fails to read PPMs produced by this project because it does not understand floating-point values).

Perhaps it'd be better to use integer values in the file, and instead specify a higher maximum value for increased precision?

P.s. existing PPMs can be converted using `sed`, though they'll be less precise:
```shell
$ sed 's/(\d+)(?:\.\d+)?/$1/' output.ppm
```

**Comment by ChristopherBiscardi** [comment]
The number does seem to be specified as "ASCII Decimal" according to https://netpbm.sourceforge.net/doc/ppm.html

and the C++ code from the Raytracing in One Weekend series casts to an int as well before writing out:

```c++
#include <iostream>

int main() {

    // Image

    int image_width = 256;
    int image_height = 256;

    // Render

    std::cout << "P3\n" << image_width << ' ' << image_height << "\n255\n";

    for (int j = 0; j < image_height; ++j) {
        for (int i = 0; i < image_width; ++i) {
            auto r = double(i) / (image_width-1);
            auto g = double(j) / (image_height-1);
            auto b = 0;

            int ir = static_cast<int>(255.999 * r);
            int ig = static_cast<int>(255.999 * g);
            int ib = static_cast<int>(255.999 * b);

            std::cout << ir << ' ' << ig << ' ' << ib << '\n';
        }
    }
}
```

**Comment by ChristopherBiscardi** [comment]
Project uses integers in the ppm file now, thanks for the issue!
